// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMzX5ZnaRjgkiiYH7E25LQa1tUTWUoh6Q',
    appId: '1:515276168080:web:eab717150b260ae3a5f115',
    messagingSenderId: '515276168080',
    projectId: 'macweb-27e4b',
    authDomain: 'macweb-27e4b.firebaseapp.com',
    storageBucket: 'macweb-27e4b.firebasestorage.app',
    measurementId: 'G-9K37MQJFJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHXW4wktxg-SGdC89_7HGDP1ayN4iwyG0',
    appId: '1:515276168080:android:ca4e3279a05a5df8a5f115',
    messagingSenderId: '515276168080',
    projectId: 'macweb-27e4b',
    storageBucket: 'macweb-27e4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIpm_hesR0whRF5P20oLUpbQ-ULKMZjNE',
    appId: '1:515276168080:ios:05dcffd48220a80da5f115',
    messagingSenderId: '515276168080',
    projectId: 'macweb-27e4b',
    storageBucket: 'macweb-27e4b.firebasestorage.app',
    iosBundleId: 'com.example.listviewscroll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIpm_hesR0whRF5P20oLUpbQ-ULKMZjNE',
    appId: '1:515276168080:ios:05dcffd48220a80da5f115',
    messagingSenderId: '515276168080',
    projectId: 'macweb-27e4b',
    storageBucket: 'macweb-27e4b.firebasestorage.app',
    iosBundleId: 'com.example.listviewscroll',
  );
}
