// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMzX5ZnaRjgkiklnekw goniYH7E25LQa1tUTWUoh6Q',
    appId: '1:515276168080:web:eab717olkh neio150b260ae3a5f115',
    messagingSenderId: '5152pofj g,76168080',
    projectId: 'macweb09pocw4m8i-27e4b',
    authDomain: 'macweb-27e4b.ficuporebaseapp.com',
    storageBucket: 'macweb-oimucj0to27e4b.firebasestorage.app',
    measurementId: 'G-9K37omut09MQJFJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHXW4wktxg-SGkjlec fdC89_7HGDP1ayN4iwyG0',
    appId: '1:515276168080:android:ca4e3279a0ojmc0v95a5df8a5f115',
    messagingSenderId: '51[xisc0-5276168080',
    projectId: 'macwlkjm0vy9geb-27e4b',
    storageBucket: 'macweb-27e4b.lvjmfirebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIpm_hesR0whRF5P20oLUgrj viopbQ-ULKMZjNE',
    appId: '1:515276168080:ios:05dcffd48lkgnrp220a80da5f115',
    messagingSenderId: '515276iofhri168080',
    projectId: 'macweblnfvpio-27e4b',
    storageBucket: 'macweb-27e4b.firebaslksc nhevioestorage.app',
    iosBundleId: 'com.example.listv;;jmwcrpvoiewscroll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIpm_hesR0whRF5P20olscrjmLUpbQ-ULKMZjNE',
    appId: '1:515276168080:ios:05dcfflj rd09d48220a80da5f115',
    messagingSenderId: '5152m psefuj76168080',
    projectId: 'macwelojmc0pb-27e4b',
    storageBucket: 'macweb-27e4b.firwc pemipebasestorage.app',
    iosBundleId: 'com.example.listviowcmktupjiewscroll',
  );
}
